config/routes.rb
Rails.application.routes.draw do
resources :polls
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/model.rb
class Model < ApplicationRecord
end

app/models/poll.rb
class Poll < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @poll = Poll.all
  end

  def create
    @poll = Poll.create(poll_params)
    redirect_to polls_path
  end

  def new
    @poll = Poll.new
  end

  def show
    @poll = Poll.find(params[:id])
  end

  def update
    @poll = Poll.find(params[:id])
    @poll.update(poll_params)
    redirect_to polls_path
  end

  def edit
    @poll = Poll.find(params[:id])
  end
  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy
    redirect_to polls_path
  end

  private
  def poll_params
    params.require(:poll).permit(:vote)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PollingSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>   
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <div class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Poller', polls_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Add poll', new_poll_path %></li>
    </ul>
  </div>
</div>
    <%= yield %>
  </body>
</html>

app/views/polls/edit.html.erb
<div class= "container">
  <%= form_for @poll do |f| %>
  <div class="form-group">
    <%= f.label :Question %>
    <%= f.text_area :vote, rows: 3, required: true, class: 'form-control' %>
  </div>
  <%= f.submit 'Create', class: 'btn btn-primary btn-lg' %>
  <% end %>
</div>

app/views/polls/index.html.erb
<div class = "container">
<%= line_chart @poll.group(:vote).count %>

<%= bar_chart @poll.group(:vote).count %>

<%= column_chart @poll.group(:vote).count %>
  <%= pie_chart @poll.group(:vote).count %>
  <% @poll.each do |poll| %>
    <div class="well">
      <h2><%= poll.vote %></h2>
      <div class="btn-group">
        <%= link_to 'Edit', edit_poll_path(poll), class: 'btn btn-default' %>
        <%= button_to 'remove' , poll_path(poll.id), method: 'delete', class: 'btn btn-danger', data: {confirm: 'Are you sure?'} %>
      </div>
  </div>
  <% end %>
</div>

app/views/polls/new.html.erb
<div class ="container">
  <div class="form-group">
  <%= form_with model: @poll do |form|%>
    <h3><strong><%= form.label :Which_is_your_favourite_pet_? %></strong></h3></br>
    <%= form.radio_button :vote, "Dog" %>
    <%= form.label :vote_dog, "Dog" %><br></br>
    <%= form.radio_button :vote, "Cat" %>
    <%= form.label :vote_cat, "Cat" %><br></br>
    <%= form.radio_button :vote, "Squirrel" %>
    <%= form.label :vote_squirrel, "Squirrel" %><br></br>
    <%= form.radio_button :vote, "None of the above" %>
    <%= form.label :vote_nothing, "None of the above" %><br></br>
    <div class="form-group">
      <%= form.submit class:"btn-primary gradient-custom-2 mb-3" %>
    </div>
  </div>
  <% end %>
</div>

app/views/polls/show.html.erb
<h1>Polls Voting </h1>
<h4><%= @poll.vote %></h4>